# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
  # cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
  # Mayor.create(name: 'Emanuel', city: cities.first)

Airport.create([{:city => 'San Francisco'}, {:country => 'USA'}, {:code => 'SFO'}, {:details => 'San Francisco International Airport offers free Wi-Fi service in all terminals. \r\n\r\nTo connect to #SFO FREE WIFI\r\n - Select the Wi-Fi network named #SFO FREE WIFI\r\n - Launch a web browser\r\n - Click the button to accept the terms and conditions\r\n'}])

Airport.create([{:city => 'London'}, {:country => 'UK'}, {:code => 'LGW'}, {:details => 'All users will get 30 minutes free use while at the airport. \r\n\r\nHigh speed wi-fi is provided at the airport by Boingo Hotspot. After connecting to the Boingo wi-fi simply open your web browser for more information and to connect.\r\n\r\nBoingo UK: a monthly subscription that gives you access in the airport as well as 580,000 other Boingo hotspots worldwide\r\n\r\nBoingo AsYouGo: for access for up to 24 hours in one location at a time\r\nBoingo Mobile: for access on smartphone.\r\n\r\nFor 24/7 customer support, contact Boingo on 0203 450 6654, on freephone 0800 032 6793 1170 (charges by mobile provider will vary), or for US-based carriers +1 800 880 41'}])

Airport.create([{:city => 'Amsterdam'}, {:country => 'The Netherlands'}, {:code => 'AMS'}, {:details => 'Amsterdam Airport Schiphol offers free WiFi access for one hour from anywhere in the airport terminal. \r\n\r\nThat means free Internet access from Schiphol Plaza and all lounges, piers and gates. \r\n\r\nTo use the free WiFi network service provided by KPN, proceed as follows:\r\n\r\nAfter starting up your laptop or mobile device, select the available network labelled ‘KPN’\r\n\r\nThe login page will ask you to select from two options: to use WiFi free of charge for one hour, select ‘free, limited-time access’. \r\n\r\nIf you would like to use the WiFi network for more than an hour, you can select the option for ‘Premium Service’.\r\n\r\nThe Premium Service is a paid, secured business service offered by KPN, and includes free printing at any KPN Internet Center at Amsterdam Airport Schiphol.\r\n\r\nPrices Premium Service\r\n15 minutes: 3 euro\r\n30 minutes: 6 euro\r\n90 minutes: 12 euro\r\nDay: 16 euro'}])

Airport.create([{:city => 'London'}, {:country => 'UK'}, {:code => 'LHR'}, {:details => 'Wi-Fi is free at Heathrow for 45 minutes for everyone\r\n\r\nTheres Wi-Fi available throughout the terminal. Just choose _Heathrow Wi-Fi and follow the on-screen instructions. \r\n\r\nMembers of our Heathrow Rewards loyalty programme get 90 minutes of free Wi-Fi. \r\n\r\nNot a member? Join at heathrow.com/rewards.\r\n\r\nPay-as-you-go Wi-Fi\r\n\r\nIf you want to stay connected when your free Wi-Fi session expires use one of our pay-as-you-go extra-time packages.'}])

Airport.create([{:city => 'Auckland'}, {:country => 'New Zealand'}, {:code => 'AKL'}, {:details => 'First 30 Minutes FREE when you register using the simple signup form provided. \r\n\r\nInstructions on how to do this are listed below:\r\n\r\nEnsure WiFi is enabled on your computer or mobile device.\r\n\r\nChoose the \"Airport Hotspot\" wireless network from the available choices.\r\n\r\nWhen presented with the login page enter your details using the 30 FREE minutes registration form.\r\n\r\nA confirmation message will then display notifying you that your session has started\r\n\r\n\r\nNote: you are able to surf the following websites free of charge:\r\n\r\nAuckland Airport - www.aucklandairport.co.nz\r\nDFS Duty Free - www.dfs.co.nz\r\nJR Duty Free - www.jrdutyfree.co.nz\r\n\r\nNeed more? \r\n\r\nAlternatively you may also pay to use our WiFi services. Once connected to the \"Airport Hotspot\" wireless network, follow the instructions on the login page to sign up for more time.'}])

Airport.create([{:city => 'Johannesburg'}, {:country => 'South Africa'}, {:code => 'JNB'}, {:details => 'The airport has wireless connectivity, with hotspots in the domestic terminal (retail- level restaurants; departures-level restaurants and boarding gates); and in international (airline lounges; international arrivals terminal; mezzanine-level restaurants; and the duty-free mall). Pay-as-you-go vouchers are available at the PostNet on the food court level.\r\n\r\nIf you don\'t have a laptop or a wi-fi card, there are also internet cafés where you can use a fixed connection network. There are two facilities in the domestic terminal (one for the general public near the ATMs on the retail level and one for passengers only beyond the security gates); and one in the international departures terminal.'}])

Airport.create([{:city => 'Istanbul'}, {:country => 'Turkey'}, {:code => 'IST'}, {:details => 'Wireless internet connections are available at the Arrivals, Departures and General Aviation terminals. \r\n\r\nThis service is free at the lounges of the Arrivals and Departures Terminals.\r\n\r\nAdditional wireless access spots within the terminal are subject to the concerned firms’ pricing policies.'}])

Airport.create([{:city => 'Athens'}, {:country => 'Greece'}, {:code => 'ATH'}, {:details => 'The Wireless Internet Zone Service is available within the airport\'s terminal areas and is offered for FREE for 45 minutes.\r\n\r\nThe brand new WiZ portal offers detailed info on your flight status, news & promos of the airport\'s Shopping Centre, the e-tv service which allows you to watch tv channels & videos on your laptop and many more. The services of the WiZ portal are provided free of charge on a 24h basis. \r\n\r\nOf course, by clicking the \"Connect to the Internet\" banner, you get free access on the Internet for 45 minutes. Upon the completion of the FREE period  further access to the internet can be provided either through the Free Internet Access Points or through the Business Centre\'s facilities at a cost (Arrivals Level)'}])

Airport.create([{:city => 'Los Angeles'}, {:country => 'USA'}, {:code => 'LAX'}, {:details => 'LAX offers free Wi-Fi to stay connected while traveling through the airport.  To access, simply access the LAX Wi-Fi and click “Get Free Access”.\r\n\r\nThe airport Wi-Fi system is available in most public areas of the airport.\r\n\r\nIn addition to free access, passengers may choose higher speed service: \r\n\r\nOptions For Premium Access\r\n• 1 Hour for $4.95\r\n• 24 hours for $7.95.\r\n\r\nAlso, passengers can use \"roaming credentials\" for subscription services.'}])

Airport.create([{:city => 'Tokyo'}, {:country => 'Japan'}, {:code => 'NRT'}, {:details => 'Narita Airport has wireless LAN Internet access throughout our passenger terminals for those who have their own computer.\r\n\r\nFor customers with their own wireless compatible computers and terminals, wireless LAN is available free of charge throughout Terminal 1 and Terminal 2. \r\n* LAN connection may be difficult in some areas. \r\n\r\n(Usage)\r\nWirelesss LAN settings → Please select SSID \"FreeWiFi-NARITA\". \r\n'}])

Airport.create([{:city => 'Paris'}, {:country => 'France'}, {:code => 'CDG'}, {:details => 'Paris-Charles de Gaulle offers you 15 minutes of free WiFi access. \r\n\r\nPurchase the amount of connection time that you want above this; you will be able to use them during different sessions at your convenience.\r\n\r\n\"Flash\" Wifi - 30 minutes for €1.90\r\n\"Convenience\" Wifi - 90 minutes for €4.50\r\n\"Unlimited\" Wifi - €9.90 \r\n\r\nFlash and Convenience Wi-Fi passes remain valid for 24 hours after your first connection'}])

Airport.create([{:city => 'Paris'}, {:country => 'France'}, {:code => 'Ory'}, {:details => 'Paris-Orly offers you 15 minutes of free WiFi access. \r\n\r\nPurchase the amount of connection time that you want above this; you will be able to use them during different sessions at your convenience.\r\n\r\n\"Flash\" Wifi - 30 minutes for €1.90\r\n\"Convenience\" Wifi - 90 minutes for €4.50\r\n\"Unlimited\" Wifi - €9.90 \r\n\r\nFlash and Convenience Wi-Fi passes remain valid for 24 hours after your first connection'}])

Airport.create([{:city => 'Sydney'}, {:country => 'Australia'}, {:code => 'SYD'}, {:details => 'Free Wi-Fi is available throughout International Terminal (T1) and Domestic Terminal (T2).\r\n\r\nRoaming providers such as Skype, Boingo and iPass are also available.\r\n\r\nSimply select “Free Internet by sponsors name & SYD” from the list of available networks, answer the questions, read the terms and conditions and click \"Proceed\". You will be shown a sponsored message then directed to a website.\r\n\r\nFrom there you can browse the internet for up to 2 hours and 500MB of data.\r\n\r\nIf you have any questions relating to the service, please contact our dedicated Wi-Fi Help Team at 1300 881 862'}])

Airport.create([{:city => 'New York'}, {:country => 'USA'}, {:code => 'JFK'}, {:details => 'At JFK Airport Terminal 6 is the place to be get free wifi internet access.\r\n\r\nTerminals 1 & 8 wi fi service is provide by Concourse and it cost $7.95. \r\n\r\nTerminals 1, 8, Terminal 4 (Avion Bar, Delancy\'s). $.12/min additional fee \r\n\r\nIn British Airways Lounges service is by Boingo and it costs $7.95. \r\n\r\n- park yourself near a JetBlue wireless hotspot sign\r\n- you have to set the SSID to \"default\" or \"any\"\r\n- accept the Terms & Conditions and you can start surfing\r\n- you will be redirected to jetblue.com for free access to the Internet.\r\n\r\nWI FI WORKAROUNDS\r\nThe Boingo network gives you 15 minutes of free internet for every 15 seconds of ads you watch but for some reason this doesn\'t work with a laptop - the only choices with boingo for a laptop all required some payment (by the hour, by the day, etc.) If a laptop is all you have maybe try spoofing your browser\'s identity to pretend you\'re an iPhone? (MobileSafari is what it might be looking for.)'}])

Airport.create([{:city => 'New York'}, {:country => 'USA'}, {:code => 'LGA'}, {:details => 'Wireless access is provided by Boingo Wireless Company. and is available in most public areas within most terminals. \r\n\r\nGet online near the ticket counters, boarding gates, designated work stations and food courts.\r\n\r\nChoose a daily plan or use your existing WiFi account.\r\n\r\nPay as you go: $4.95 per hour\r\nDay Pass: Unlimited access for a 24-hour period, $7.95\r\nUnlimited Access: Sign up for a monthly subscription and get unlimited access at more than 100,000 hotspots worldwide, $9.95 per month\r\n\r\nExisting WiFi Account: If you have an existing WiFi account, you can connect using your user name and password\r\n\r\nCustomer service is available seven days a week, 24 hours per day. Call toll free (800) 550-5030.'}])

Airport.create([{:city => 'Minneapolis'}, {:country => 'USA'}, {:code => 'MSP'}, {:details => 'Complimentary Wireless Internet Access (WiFi) is available in all public areas of both terminals, once you pass through security. \r\n\r\nWatch a brief advertisement or take a short survey followed by 45 minutes of complimentary WiFi service. A timer will remind you of the session time that remains. Once the session expires, customers can view another sponsored advertisement or take another quick survey in order to continue using complimentary Wi-Fi. Travelers can enjoy as many of these free sessions as they choose while visiting MSP.\r\n\r\nFor those preferring an uninterrupted, commercial-free experience or a session with greater bandwidth and four times the speed, a premium service is available for only $2.95 for 24-hour use.'}])

Airport.create([{:city => 'Melbourne'}, {:country => 'Australia'}, {:code => 'MEL'}, {:details => 'Free WIFI - \"FREE WIFI by MEL\"\r\n\r\nMelbourne Airport now offers free Wi-Fi access throughout our terminals. Available in all public areas and aircraft gate lounges*, the free Wi-Fi hotspot includes Terminal 2, 3 and 4 (Qantas also provides a free Wi-Fi connection within Terminal 1).\r\n\r\n* Gates 12-20 in Terminal 2 may experience a reduction in signal strength. If this occurs please move towards the main terminal area or consider using the paid Wi-Fi service.\r\n\r\nSimply connect to the “FREE WIFI by MEL” network and answer a few short survey questions to commence your session. Please refer to our terms and conditions for Wi-Fi usage.\r\n\r\nIt is important to note that the free Wi-Fi service is not encrypted, so please consider the security of your personal information when using the free service.\r\n\r\nTo assist you in connecting to the free Wi-Fi, we recommend the below:\r\n• Ensure you are on the latest version of the mobile device operating system. Please refer to your operating manual for instructions on how to update your device\r\n• Clear browser cookies and cache (browsing history)\r\n• Turn ON cookies (at least from visited web sites)\r\n• Turn OFF private browsing \r\n• Set your IP address settings to automatic\r\n• Close unnecessary applications to free mobile device memory \r\n• Disable data service (eg. GPRS or 3G) to avoid a roaming service fee\r\n• Select \"FREE WIFI by MEL\" as your connection network (SSID)\r\n• Launch an internet browser and enter any valid website address to use the Wi-Fi\r\n• Disconnect your device from the Wi-Fi network after use\r\n\r\n\r\nPaid WIFI - \"MELBOURNE AIRPORT\"\r\n\r\nYou can also use your Visa, MasterCard, American Express, or Diners Club card to purchase a timed Internet access session. All you need to do is turn on the 802.11b/g wireless capability of your laptop, PDA or mobile phone, connect to the \"MELBOURNE AIRPORT\" SSID in your wireless settings, and open up a web browser. Select the access time period required and follow the payment instructions. Once payment is confirmed, you will be redirected to the Melbourne Airport wireless hotspot home page to enjoy your internet access.\r\n\r\nPlease note that an SMTP address is not available and remember to log off at the end of your session using the pop-up box which appears when you log in.\r\n\r\nCharges\r\n\r\nTime (minutes)\tCost (AUD$)\r\n15\t- 4.00\r\n30\t- 6.00\r\n60\t- 11.00\r\n120\t- 20.00\r\n'}])

Airport.create([{:city => 'Frankfurt'}, {:country => 'Germany'}, {:code => 'FRA'}, {:details => 'You can access the Internet via Frankfurt Airport’s Wi-Fi network for 30 minutes at no charge. \r\n\r\nAfterward it is of course possible to request another access code and pay for it on www.hotspot.de; 24 hours of online time costs 4.95 euros.\r\n\r\nThere are also sit-down Internet Points and Internet Towers (for use standing up) that you can use to conveniently surf the Web.\r\n\r\nOpen a browser window on your own laptop or smartphone, which takes you straight to the registration page. There you fill in your e-mail address. \r\n\r\nYou can use the Wi-Fi network once per day.'}])

Airport.create([{:city => 'Bangkok'}, {:country => 'Thailand'}, {:code => 'BKK'}, {:details => 'Suvarnabhumi Airport has free Wi-Fi access throughout the airport.\r\n\r\nAlso 126 high-speed Internet kiosks installed by CAT Telecom. The kiosks feature fast 10 Mbps Internet access and will be free-of-charge for tourists.\r\n\r\nUsage on the terminals will be limited to 15-minute sessions, which will end automatically.'}])

